# Generated by Django 3.1.5 on 2021-03-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ca298app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='picture',
            field=models.FileField(blank=True, upload_to='category_img/'),
        ),
    ]
